framework:
    http_method_override: true
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
    # ⬇ Force le schéma HTTPS
    trusted_headers:
        - "x-forwarded-for"
        - "x-forwarded-proto"
        - "x-forwarded-port"


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
