services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - symfony-network

  db:
    image: postgres:16-alpine
    container_name: symfony-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony-network

  nginx:
    image: nginx:alpine
    container_name: symfony-nginx
    expose:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - symfony-network

volumes:
  db_data:

networks:
  symfony-network:
